# Generated by Django 6.0.4 on 2026-04-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(choices=[('Control', 'Control'), ('Consulta Nueva', 'Consulta Nueva'), ('Primera Vez', 'Primera Vez'), ('Urgencia', 'Urgencia')], max_length=255)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('en_espera', 'En espera'), ('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=50)),
                ('fecha_pautada', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('seguro', 'Seguro')], max_length=50)),
                ('estado_pago', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('anulado', 'Anulado')], default='pendiente', max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
