# Generated by Django 6.0.4 on 2026-04-21 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirugias', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('alergias', models.ManyToManyField(blank=True, related_name='historiales', to='patients.allergy')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_history', to='patients.patient')),
                ('patologias', models.ManyToManyField(blank=True, related_name='historiales', to='patients.pathology')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjetivo', models.TextField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('analisis', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('saturacion_oxigeno', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=50)),
                ('fecha_realizada', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
            ],
        ),
    ]
